Add aiohttp
The github testing started failing due to:
ModuleNotFoundError: No module named 'aiohttp'

I wasn't able to reproduce locally, so attempting to see if this
solves the problem